### PR TITLE
Add Cybersecurity Teaching Pages

### PR DESCRIPTION
**Pull request by urmomstoaster**

### CODE REVIEW

**Review by iamalmiir — CHANGES_REQUESTED** [review]
Code looks great. But I think it would be good if you turn this into react components. If files are not ending with .js Next framework will not be able to recognize the path. Maybe I'm missing something. Additionally I can make those changes if needed.

**Review by iamalmiir — CHANGES_REQUESTED** [review]
Please refer to the rest of the project. We need to stay consistent across the project so that everyone after us can contribute. Even if this can work it's not considered the best practice. Please don't let this discourage you to contribute.

**Comment by urmomstoaster** [comment]
I'm not aiming for this to be something that can be altered, I'm making this purely for people to practice the fundamentals of Cybersecurity with. I can understand cohesiveness of regular commits, these are simply pages meant for demonstration purposes.

**Comment by iamalmiir** [comment]
Hey, thank you for your response. Whatever the idea is (I like the idea and it should be included) it needs to be put in the components if it's going to be the part of the official website. Maybe we can work things out and find the better solution for this together. I hope this helps.

**Comment by urmomstoaster** [comment]
I have discussed routing with President Peter and he has approved this. I appreciate your fight for best practice however this is not that important of a page, they're primarily serving as last-minute presentation supplements and are unlikely to be improved on in this state in the future.

**Comment by urmomstoaster** [comment]
These pages are temporary for the next meeting in less than 24 hours so we can simply remove them later at this rate

**Pull request merged**
